=== AG-Akash-Goyal/WSD/lab3.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Interior-Design-Website">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Customer" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="C_ID" type="xs:string"/>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Age" type="xs:int"/>
                            <xs:element name="Gender" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Design" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="D_ID" type="xs:string"/>
                            <xs:element name="Price" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AG-Akash-Goyal/WSD/lab3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet href="lab3.xsl" type="text/xsl"?>
<Interior-Design-Website xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lab3.xsd">
    
    <Customer>
        <C_ID>C01</C_ID>
        <Name>Akash Goyal</Name>
        <Age>21</Age>
        <Gender>M</Gender>
    </Customer>

    <Customer>
        <C_ID>C02</C_ID>
        <Name>Amisha Sehgal</Name>
        <Age>20</Age>
        <Gender>F</Gender>
    </Customer>

    <Design>
        <D_ID>D01</D_ID>
        <Price>23000</Price>
    </Design>

    <Design>
        <D_ID>D02</D_ID>
        <Price>9999</Price>
    </Design>
</Interior-Design-Website>
